### ISSUE TITLE
Unwanted empty lines in Kommentare

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/ocr-gt-tools#34]
If the Kommentar field is non-empty or was non-empty before, then adding "Kursiv" etc. will generate additional empty lines. To reproduce try this:
1. Go to a new line and open the Kommentar
2. Write some text in the Kommentar (and delete it again)
3. Click on "Kursiv"

**Comment by kba** [comment]
Since this is tricky to get right, I implemented a compromise: The ugly newlines are still created but are removed (also in the view) when the page is saved.

**Comment by kba** [comment]
Should be fixed now: contenteditable lines are reformatted on losing focus or save.
