### ISSUE TITLE
Alignment of buttons to line

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/ocr-gt-tools#35]
Sometimes it is quite hard to see which button correspond to which line. From the current alignment/layout it could correspond to the line above OR below. Cf.

![standard-kommentare](https://cloud.githubusercontent.com/assets/5199995/14820928/07d0fd2c-0bc9-11e6-871f-46146f08e538.png)

**Comment by kba** [comment]
Right now, the buttons are in the title bar of the line. So they are always on top of line below.

What do you propose?
- Highlight the current line (=title bar, image, transcription, comment) on mouse hover
- Float the buttons right in the level of the images and break them if the image is too wide
- In general, hide the buttons of the non-focussed line

I'm open to suggestions :)

**Comment by kba** [comment]
This is how it looks at the moment:

![screenshot_2016-04-28_15-35-54](https://cloud.githubusercontent.com/assets/273367/14887671/1ae8c5ae-0d57-11e6-9902-f3a509e207d9.png)

![screenshot_2016-04-28_15-39-06](https://cloud.githubusercontent.com/assets/273367/14887759/69a6c7ea-0d57-11e6-94e8-7ab4e3089091.png)

**Comment by zuphilip** [comment]
Wow, yeah, I like the new layout!

If you like we can close the issue here with this.
