### ISSUE TITLE
Kommentar always activate when newline was typed

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/ocr-gt-tools#36]
Try this to reproduce:
1. Goto a new line, open Kommentar
2. Write `line1`, press return for a new line, write `line2`
3. Delete this text again completely

And you will see that the Kommentar is still activated also it is empty.

**Comment by kba** [comment]
What do you mean with

>  the Kommentar is still activated also it is empty.

Following the steps you describe, I now have an empty comment field. What is the desired outcome for you?

**Comment by zuphilip** [comment]
Yes, but it is still blue.

**Comment by kba** [comment]
I see now. This doesn't happen in the dev version, only in the currently deployed version. Let's see whether problem is gone with next pull.

**Comment by kba** [comment]
Firefox issue. Still insert `<br>`
