### ISSUE TITLE
Tab key stops at second button

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/ocr-gt-tools#42]
It is handy if one can go through all text input lines with tab key. If you start in a text line and press tab, then you will focus on the second button (exclamation mark) and you need an additional tab to focus on the next text line.

**Comment by LetschM** [comment]
This would indeed be very useful. Maybe we also could exclude the comment lines from tab focus, so if someone already commented on lines (like first marking all italic text lines before writing) and afterwards wrties along on the transcription line, he could "jump" over the already opened comment lines to the next transcription line.

**Comment by kba** [comment]
> exclude the comment lines from tab focus

Easily implemented. This would mean that you'd need to use the mouse to select the comment field. @zuphilip @stweil @BFallert Is this what we want?

**Comment by zuphilip** [comment]
I don't think we should exclude the comment lines.

>  if someone already commented on lines (like first marking all italic text lines before writing) and afterwards wrties along on the transcription line, he could "jump" over the already opened comment lines to the next transcription line.

Well, in this use case the person can just hide the comments and concentrate on the transcription.

**Comment by stweil** [comment]
Yes. It's fine to ignore closed comment lines, but if they are open, I'd expect that they can be reached with the keyboard.
