### ISSUE TITLE
Is "Alle Einklappen/Ausklappen" still useful?

### ISSUE THREAD

**Issue by zuphilip** [UB-Mannheim/ocr-gt-tools#43]
We can do more or less the same with hiding/showing the comments from the view menu. Well, it is not exactly the same, therefore I would like to ask if there are still some use cases for Ein-/Ausklappen. 

It seems for me that the only functionality we might lose is to reopen/show all comments if some of them have been collapsed/hidden.

We could also think about showing always the comments if they are not empty, because we can then still hide all comments.

**Comment by kba** [comment]
> Well, it is not exactly the same, therefore I would like to ask if there are still some use cases for Ein-/Ausklappen. 

It's indeed very similar. I would prefer to get rid of the collapse/expand buttons because they add another layer of hiding/showing elements which can conflict.

> We could also think about showing always the comments if they are not empty, because we can then still hide all comments.

That was the behavior before, I reverted it to "all-closed on page load" because that's how it was originally. Can change that.
