### ISSUE TITLE
Internal Server Error when trying to save OCR-GT file

### ISSUE THREAD

**Issue by LetschM** [UB-Mannheim/ocr-gt-tools#59]
http://digi.bib.uni-mannheim.de/ocr-gt/#http://digi.bib.uni-mannheim.de/fileadmin/digi/426116992/thumbs/426116992_0335.jpg

When trying to save the edited file in digi.bib.uni-mannheim.de/ocr-gt by hitting the save button, recently the following HTTP error 500 note occurs:

![screenshot_2016-05-17_11-02-50](https://cloud.githubusercontent.com/assets/6389153/15316809/eadd09ac-1c1e-11e6-819d-e3748e0a32c5.png)

right before the first time this error note occurred I did the following things:
1. Edit the text lines and adding text-italic and wrong-image-section comments
2. Switch the view to "Bild+Kommentar"
3. Delete some falsely set comments in the comment lines
4. adding some new comments by clicking "wrong-image-section" and "text-italic" buttons
5. Clicking "Save" button
--> Error occurred

**Comment by kba** [comment]
Problem are unescaped regex characters in the transliteration, like `) [ \d` etc. Not yet fully fixed.
