### ISSUE TITLE
Transcription of spaces

### ISSUE THREAD

**Issue by kba** [UB-Mannheim/ocr-gt-tools#66]
E.g. header line in http://digi.bib.uni-mannheim.de/fileadmin/digi/445441798/max/445441798_0016.jpg

```
14␣Tractatus
```

vs

```
14␣␣␣␣␣␣␣␣␣␣␣Tractatus
```

**Comment by zuphilip** [comment]
Our rules say that that doesn't matter whether there are 1 or many spaces. We should suggest maybe another [`kind`](https://github.com/tmbdev/ocropy/blob/master/ocropus-errs#L18) of comparison in `ocropus-errs` which will delete multiple spaces (but let 1 space intact), i.e.

``` python
    if kind=="nomultiplespace":
        return re.sub(ur'\s+','\s',s)
```

in https://github.com/tmbdev/ocropy/blob/master/ocrolib/common.py#L126

**Comment by kba** [comment]
@zuphilip Good idea. Maybe create an issue [in ocropy](/tmbdev/ocropy/issues) to keep track of it?

**Comment by zuphilip** [comment]
I created an issue in ocropus repo: https://github.com/tmbdev/ocropy/issues/98
