### ISSUE TITLE
Small errors in INSTALL.md

### ISSUE THREAD

**Issue by pbroman** [UB-Mannheim/ocr-gt-tools#83]
FYI: Installing ocr-gt-tools under Apache I found the following small errors in INSTALL.md
* make dist/vendor: target doesn't exist in Makefile
* make vendor: doesn't work since variable GIT_CLONE not set
* In dev/apache.mk, the APACHE_DIR is set to ocr-gt, in URLs and apache conf snippet in INSTALL.md to ocr-gt-tools

**Comment by zuphilip** [comment]
Thank you for the report. The GIT_CLONE was delete in one commit and this should be
```
# Git clone, by default do a shallow clone, only last commit
GIT_CLONE     = git clone --depth 1
```

Did you fix the other issues too? Do you want to send a PR?

**Comment by stweil** [comment]
Pull request #83 which fixes this issue is merged now, therefore I close the issue. Thanks again for reporting and fixing this.
