### ISSUE TITLE
ocropus-gtedit: invalid choice 'xxx'

### ISSUE THREAD

**Issue by kba** [UB-Mannheim/ocr-gt-tools#9]
In [erzeuge_files 120](https://github.com/UB-Mannheim/ocr-gt-tools/blob/master/erzeuge_files.pl#L120), `ocropus-edit` wird mit `-x xxx` aufgerufen. Das liefert für mich diesen Fehler:

```
usage: ocropus-gtedit [-h] {write,text,org,html,extract} ...
ocropus-gtedit: error: argument subparser_name: invalid choice: 'xxx' (choose from 'write', 'text', 'org', 'html', 'extract')
```

Müsste wohl `-x html` sein, oder?

**Comment by zuphilip** [comment]
Das sind zwei Optionen: `ocropus-gtedit html -x xxx`. Dabei ist `html` ein Unterkommando von `ocropus-gtedit` und mit `-x` wird die Dateiendung angegeben für die Datei für das Befüllen der Texteingaben angeben, welche wir aber nicht wollen (daher die fiktive Dateiendung `xxx`).

**Comment by zuphilip** [comment]
vgl. https://github.com/tmbdev/ocropy/wiki/Working-with-Ground-Truth

**Comment by kba** [comment]
Mein Fehler, das `html` hab ich in meiner branch versehentlich gelöscht. :blush:
